devSearch/urls.py
from django.contrib import admin

from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"),
         name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"),
         name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('projects/', views.projects, name='projects'),
    path('projects/<int:id>', views.singleProject, name='single-project'),

    path('messages/', views.inbox, name='inbox'),
    path('messages/<int:id>', views.singleMessage, name='message'),
    path('messages/send/<int:user_id>', views.sendMessage, name='send-message'),
]

users/models.py
from django.db import models

from django.contrib.auth.models import User


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='/avatars/default.jpg', upload_to='avatars')
    summary = models.TextField('Summary about user', default='New user on our platform!')
    location = models.TextField('Place of residence', default='Location is not specified.')
    about = models.TextField('About', default='Apparently, this user prefers to keep an air of mystery about them.')
    other_skills = models.TextField('Other skills', null=True, blank=True, help_text='Comma-separated skills')

    def __str__(self):
        return f'{self.user.username} Account'


class Skill(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    name = models.CharField('Skill name', max_length=20)
    description = models.TextField('Skill description')

    def __str__(self):
        return f'{self.account} - {self.name} Skill'


class Link(models.Model):
    ICONS = (
        ('im im-github', 'GitHub'),
        ('im im-stackoverflow', 'StackOverflow'),
        ('im im-linkedin', 'LinkedIn'),
        ('im im-twitter', 'Twitter'),
        ('im im-globe', 'Website')
    )
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    name = models.CharField('Link name', max_length=30)
    link = models.URLField('URL')
    icon = models.TextField('Icon name', choices=ICONS)

    def __str__(self):
        return f'{self.name} Link'

templates/account-edit-form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
  <!-- Icon - IconMonster -->
  <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
  <!-- Mumble UI -->
  <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="{% static 'styles/app.css' %}" />

    <title>DevNet - Connect with Developers!</title>
</head>

<body>
    <!-- Header Section -->
    <header class="header">
        <div class="container container--narrow">
            <a href="/" class="header__logo">
                <img src="{% static 'images/logo.svg' %}" alt="DevNet Logo" />
            </a>
            <nav class="header__nav">
                <input type="checkbox" id="responsive-menu" />
                <label for="responsive-menu" class="toggle-menu">
                    <span>Menu</span>
                    <div class="toggle-menu__lines"></div>
                </label>
                <ul class="header__menu">
                    <li class="header__menuItem"><a href="{% url 'index' %}">Developers</a></li>
                    <li class="header__menuItem"><a href="{% url 'projects' %}">Projects</a></li>
                    <li class="header__menuItem"><a href="inbox.html">Inbox</a></li>
                    <li class="header__menuItem"><a href="{% url 'account' %}">My Account</a></li>
                   {% if request.user.username %}
                       <li class="header__menuItem"><a href="{% url 'logout' %}" class="btn btn--sub">Log Out</a></li>
                    {% else %}
                       <li class="header__menuItem"><a href="{% url 'login' %}" class="btn btn--sub">Login/Sign Up</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </header>

    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">Full Name: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="full_name" required
                            value="{{ user.first_name }} {{ user.last_name }}" />
                    </div>

                    <div class="form__field">
                        <label for="formInput#text">Email: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="email" required
                            value="{{ user.email }}" />
                    </div>

                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">Summary: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="summary" required
                            value="{{ user.account.summary }}" />
                    </div>

                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">Location: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="location" required
                            value="{{ user.account.location }}" />
                    </div>

                    <div class="form__field">
                        <label for="formInput#text">About: </label>
                        <textarea class="input input--text" id="formInput#text" type="text" name="about" required>{{ user.account.about }}</textarea>
                    </div>

                    <div class="form__field">
                        <label for="formInput#text">Skills: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="skills" required
                            value="{% for skill in user.account.other_skills %}{{ skill }}, {% endfor %}" />
                    </div>

                    <div class="form__field">
                        <label for="formInput#text">Avatar: </label>
                        <input class="input input--text" id="formInput#text" type="file" accept="image/*" name="avatar"/>
                    </div>
                    {% for msg in messages %}
                        <p>{{ msg }}</p>
                    {% endfor %}
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>
</body>

</html>

templates/account.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
  <!-- Icon - IconMonster -->
  <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
  <!-- Mumble UI -->
  <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="{% static 'styles/app.css' %}" />

  <title>DevNet - Connect with Developers!</title>
</head>

<body>
  <!-- Header Section -->
  <header class="header">
    <div class="container container--narrow">
      <a href="/" class="header__logo">
        <img src="{% static 'images/logo.svg' %}" alt="DevNet Logo" />
      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          <li class="header__menuItem"><a href="{% url 'index' %}">Developers</a></li>
          <li class="header__menuItem"><a href="{% url 'projects' %}">Projects</a></li>
          <li class="header__menuItem"><a href="{% url 'inbox' %}">Inbox</a></li>
          <li class="header__menuItem"><a href="{% url 'account' %}">My Account</a></li>
          {% if request.user.username %}
            <li class="header__menuItem"><a href="{% url 'logout' %}" class="btn btn--sub">Log Out</a></li>
          {% else %}
            <li class="header__menuItem"><a href="{% url 'login' %}" class="btn btn--sub">Login/Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </header>

  <!-- Main Section -->
  <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit-account' %}"><i class="im im-edit"></i> Edit</a>
              <img class="avatar avatar--xl dev__avatar" src="{{ user.account.avatar.url }}" />
              <h2 class="dev__name">{{ user.first_name }} {{ user.last_name }}</h2>
              <p class="dev__title">{{ user.account.summary }}</p>
              <p class="dev__location">{{ user.account.location }}</p>
              <ul class="dev__social">
                {% for link in user.link_set.all %}
                    <li>
                      <a title="{{ link.name }}" href="{{ link.link }}" target="_blank"><i class="{{ link.icon }}"></i></a>
                    </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
                {{ user.account.about }}
            </p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'add-skill' %}"><i class="im im-plus"></i> Add Skill</a>
          </div>

          <table class="settings__table">
            {% for skill in user.account.skill_set.all %}
            <tr>
              <td class="settings__tableInfo">
                <h4>{{ skill.name }}</h4>
                <p>
                    {{ skill.description }}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit-skill' skill.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-skill' skill.id %}"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
              {% endfor %}
          </table>

          <div class="settings">
            <h3 class="settings__title">Projects</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'add-project' %}"><i class="im im-plus"></i> Add Project</a>
          </div>

          <table class="settings__table">
              {% for project in projects %}
                <tr>
                  <td class="settings__thumbnail">
                    <a href="{% url 'single-project' project.id %}"><img src="{{ project.image.url }}" alt="Project Thumbnail" /></a>
                  </td>
                  <td class="settings__tableInfo">
                    <a href="{% url 'single-project' project.id %}">{{ project.title }}</a>
                    <p>
                        {{ project.description }}
                    </p>
                  </td>
                  <td class="settings__tableActions">
                    <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit-project' project.id %}"><i class="im im-edit"></i> Edit</a>
                    <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-project' project.id %}"><i class="im im-x-mark-circle-o"></i>
                      Delete</a>
                  </td>
                </tr>
              {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </main>
</body>

</html>

templates/delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
  <!-- Icon - IconMonster -->
  <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
  <!-- Mumble UI -->
  <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="{% static 'styles/app.css' %}" />

    <title>DevNet - Connect with Developers!</title>
</head>

<body>
    <!-- Header Section -->
    <header class="header">
        <div class="container container--narrow">
            <a href="{% url 'index' %}" class="header__logo">
                <img src="{% static 'images/logo.svg' %}" alt="DevNet Logo" />
            </a>
            <nav class="header__nav">
                <input type="checkbox" id="responsive-menu" />
                <label for="responsive-menu" class="toggle-menu">
                    <span>Menu</span>
                    <div class="toggle-menu__lines"></div>
                </label>
                <ul class="header__menu">
                    <li class="header__menuItem"><a href="{% url 'index' %}">Developers</a></li>
                    <li class="header__menuItem"><a href="projects.html">Projects</a></li>
                    <li class="header__menuItem"><a href="{% url 'inbox' %}">Inbox</a></li>
                    <li class="header__menuItem"><a href="{% url 'account' %}">My Account</a></li>
                    {% if request.user.username %}
                       <li class="header__menuItem"><a href="{% url 'logout' %}" class="btn btn--sub">Log Out</a></li>
                    {% else %}
                       <li class="header__menuItem"><a href="{% url 'login' %}" class="btn btn--sub">Login/Sign Up</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </header>

    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" method="POST">
                    {% csrf_token %}
                    <p>{{ warning }}</p>
                    <a class="btn btn--sub btn--lg  my-md" href="{% url 'account' %}">&#x2190 Go Back</a>
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Delete" />
                </form>
            </div>
        </div>
    </main>
</body>

</html>

templates/forgetpassword.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Favicon -->
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
  <!-- Icon - IconMonster -->
  <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
  <!-- Mumble UI -->
  <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="{% static 'styles/app.css' %}" />

    <title>DevNet - Connect with Developers!</title>
  </head>

  <body>
    <div class="auth">
      <div class="card">
        <div class="auth__header text-center">
          <a href="/">
            <img src="{% static 'images/logo.svg' %}" alt="DevNet Logo" />
          </a>
          <h3>Forget Password?</h3>
          <p>Reset password by entering the email address</p>
        </div>

        <form action="#" class="form auth__form">
          <!-- Input:Email -->
          <div class="form__field">
            <label for="formInput#email">Email Address: </label>
            <input
              class="input input--email"
              id="formInput#email"
              type="email"
              name="email"
              placeholder="e.g. user@domain.com"
            />
          </div>

          <div class="auth__actions">
            <input class="btn btn--sub btn--lg" type="submit" value="Send Instructions" />
            <a href="login.html">Login</a>
          </div>
        </form>
        <div class="auth__alternative">
          <p>Don’t have an Account?</p>
          <a href="signup.html">Sign Up</a>
        </div>
      </div>
    </div>
  </body>
</html>

templates/inbox.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
  <!-- Icon - IconMonster -->
  <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
  <!-- Mumble UI -->
  <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="{% static 'styles/app.css' %}" />

  <title>DevNet - Connect with Developers!</title>
</head>

<body>
  <!-- Header Section -->
  <header class="header">
    <div class="container container--narrow">
      <a href="/" class="header__logo">
        <img src="{% static 'images/logo.svg' %}" alt="DevNet Logo" />
      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          <li class="header__menuItem"><a href="{% url 'index' %}">Developers</a></li>
          <li class="header__menuItem"><a href="{% url 'projects' %}">Projects</a></li>
          <li class="header__menuItem"><a href="{% url 'inbox' %}">Inbox</a></li>
          <li class="header__menuItem"><a href="{% url 'account' %}">My Account</a></li>
          {% if request.user.username %}
            <li class="header__menuItem"><a href="{% url 'logout' %}" class="btn btn--sub">Log Out</a></li>
          {% else %}
            <li class="header__menuItem"><a href="{% url 'login' %}" class="btn btn--sub">Login/Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </header>

  <!-- Main Section -->
  <main class="inbox my-xl">
    <div class="content-box">
      <h3 class="inbox__title">New Messages(<span>{{ unread }}</span>)</h3>
      <ul class="messages">
         {% for message in messages %}
             {% if message.is_read %}
                <li class="message message">
             {% else %}
                 <li class="message message--unread">
             {% endif %}
              <a href="{% url 'message' message.id %}">
                <span class="message__author">{{ message.user_from.first_name }} {{ message.user_from.last_name }}</span>
                <span class="message__subject">{{ message.subject }}</span>
                <span class="message__date">{{ message.date }}</span>
              </a>
            </li>
         {% endfor %}
      </ul>
    </div>
  </main>
</body>

</html>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
  <!-- Icon - IconMonster -->
  <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
  <!-- Mumble UI -->
  <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="{% static 'styles/app.css' %}" />

  <title>DevNet - Connect with Developers!</title>
</head>

<body>
  <!-- Header Section -->
  <header class="header">
    <div class="container container--narrow">
      <a href="/" class="header__logo">
        <h1 class="logo">DevNet</h1>

      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          <li class="header__menuItem"><a href="{% url 'index' %}">Developers</a></li>
          <li class="header__menuItem"><a href="{% url 'projects' %}">Projects</a></li>
          <li class="header__menuItem"><a href="{% url 'inbox' %}">Inbox</a></li>
          <li class="header__menuItem"><a href="{% url 'account' %}">My Account</a></li>
          {% if request.user.username %}
            <li class="header__menuItem"><a href="{% url 'logout' %}" class="btn btn--sub">Log Out</a></li>
          {% else %}
            <li class="header__menuItem"><a href="{% url 'login' %}" class="btn btn--sub">Login/Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </header>

  <!-- Main Section -->
  <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form class="form" method="post">
            {% csrf_token %}
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="search"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">

        {% for user in users %}
          <div class="column card">
            <div class="dev">
              <a href="{% url 'profile' user.username %}" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="{{ user.account.avatar.url }}" alt="image" />
                  <div class="dev__meta">
                    <h3>{{ user.first_name }} {{ user.last_name }}</h3>
                    <h5>{{ user.account.summary }}</h5>
                  </div>
                </div>
                <p class="dev__info">{{ user.account.about }}</p>
                <div class="dev__skills">
                    {% for skill in user.account.skill_set.all %}
                      <span class="tag tag--pill tag--main">
                        <small>{{ skill.name }}</small>
                      </span>
                    {% endfor %}
                </div>
              </a>
            </div>
          </div>
        {% endfor %}
        </div>
      </div>
    </section>

    <div class="pagination">
      <ul class="container">
      {% if users.has_previous %}
        <li><a href="{% url 'index' %}?page={{ users.previous_page_number }}" class="btn">&#10094; Prev</a></li>
      {% else %}
          <li><a class="btn btn--disabled">&#10094; Prev</a></li>
      {% endif %}

          {% for page in users.paginator.page_range %}
            {% if users.number == page %}
                <li><a href="{% url 'index' %}?page={{ page }}" class="btn btn--sub">{{ page }}</a></li>
            {% else %}
                <li><a href="{% url 'index' %}?page={{ page }}" class="btn">{{ page }}</a></li>
            {% endif %}
          {% endfor %}

      {% if users.has_next %}
        <li><a href="{% url 'index' %}?page={{ users.next_page_number }}" class="btn">Next &#10095;</a></li>
      {% else %}
          <li><a class="btn btn--disabled">Next &#10095;</a></li>
      {% endif %}
      </ul>
    </div>
  </main>
</body>

</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
  <!-- Icon - IconMonster -->
  <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
  <!-- Mumble UI -->
  <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="{% static 'styles/app.css' %}" />

    <title>DevNet - Connect with Developers!</title>
  </head>

  <body>
    <div class="auth">
      <div class="card">
        <div class="auth__header text-center">
          <a href="{% url 'index' %}">
            <img src="{% static 'images/icon.svg' %}" alt="icon" />
          </a>
          <h3>Account Login</h3>
          <p>Hello Developer, Welcome Back!</p>
        </div>

        <form class="form auth__form" method="post">
          {% csrf_token %}
          <!-- Input:Email -->
          <div class="form__field">
            <label for="formInput#text">Email: </label>
            <input
              class="input input--text"
              id="formInput#text"
              type="text"
              name="email"
              placeholder="Enter your email..."
            />
          </div>

          <!-- Input:Password -->
          <div class="form__field">
            <label for="formInput#password">Password: </label>
            <input
              class="input input--password"
              id="formInput#passowrd"
              type="password"
              name="password"
              placeholder="••••••••"
            />
          </div>
          <div class="auth__actions">
            <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
            <a href="{% url 'reset_password' %}">Forget Password?</a>
          </div>
          {% for msg in messages %}
              <p>{{ msg }}</p>
          {% endfor %}
        </form>
        <div class="auth__alternative">
          <p>Don’t have an Account?</p>
          <a href="{% url 'singup' %}">Sign Up</a>
        </div>
      </div>
    </div>
  </body>
</html>

templates/reset_password_complete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
  <!-- Icon - IconMonster -->
  <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
  <!-- Mumble UI -->
  <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="{% static 'styles/app.css' %}" />

    <title>DevNet - Connect with Developers!</title>
  </head>

  <body>

    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <h3>Password reset complete</h3>

                <p>Your password has been set. You may go ahead and log in now.</p>
                <br>
                <a href="{% url 'login' %}">Login</a>
            </div>
        </div>
    </main>

  </body>
</html>